spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  jdbc:
    config:
      url: jdbc:postgresql://192.168.137.10:5432/game_base_background
      username: postgres
      password: test
      driver-class-name: org.postgresql.Driver
      show-sql: true
      ddl-auto: "update"

