spring:
  jpa:
    database: h2
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  jdbc:
    config:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:file:./target/database/game1
      username: root
      password: test
      show-sql: false
      ddl-auto: "update"


