spring:
  redis:
    config:
      host: 192.168.137.10
      port: 6379
      password:
      database: 0 #数据库插槽
      timeout: 5000
      lettuce:
        pool:
          max-active: 50 # 最大连接数
          max-idle: 50 # 最大空闲连接数
          min-idle: 50 # 最小空闲连接数
          max-wait: 3000 # 最大等待时间，单位毫秒

  redis2:
    config:
      host: 192.168.137.10
      port: 6379
      password:
      database: 1 #数据库插槽
      timeout: 5000
      lettuce:
        pool:
          max-active: 50 # 最大连接数
          max-idle: 50 # 最大空闲连接数
          min-idle: 50 # 最小空闲连接数
          max-wait: 3000 # 最大等待时间，单位毫秒