spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  jdbc:
    config:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.137.10:5432/background_logs
      username: postgres
      password: test
      show-sql: true
      ddl-auto: "update"

